[opener]

edit = [
    { run = 'nvim %s', block = true, desc = "Edit" }
]

image = [
    { run = 'imv-wayland %s', orphan = true, desc = "View" }
]

pdf = [
    { run = 'zathura %s', orphan = true, desc = "View" }
]

[open]

prepend_rules = [
    { mime = "text/*", use = "edit" },
    { mime = "image/*", use = "image" },
    { mime = "application/pdf", use = "pdf" },
]
